[target.'cfg(all())']
rustflags = [
    "-Dclippy::all",
    "-Dlet_underscore_drop",
    "-Aclippy::assertions_on_result_states",
    "-Aclippy::let_unit_value",
]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-Zlinker-features=-lld"] # fix nightly bug https://github.com/rust-lang/rust/issues/125321
